[target.'cfg(all())']
rustflags = [
    # Complexity Group
    "-Aclippy::manual_c_str_literals",

    # Style Group
    "-Aclippy::missing_safety_doc",

    # Suspicious Group
    "-Aclippy::incompatible_msrv",
    "-Aclippy::missing_transmute_annotations",
    "-Aclippy::macro_metavars_in_unsafe",

    # Perf Group
    "-Aclippy::result_large_err",
    "-Aclippy::large_enum_variant",

    # Cargo Group
    "-Wclippy::negative_feature_names",
    "-Wclippy::redundant_feature_names",
    "-Wclippy::wildcard_dependencies",

    # Nursery Group
    "-Wclippy::branches_sharing_code",
    "-Wclippy::clear_with_drain",
    "-Wclippy::collection_is_never_read",
    "-Wclippy::debug_assert_with_mut_call",
    "-Wclippy::derive_partial_eq_without_eq",
    "-Wclippy::future_not_send",
    "-Wclippy::iter_on_empty_collections",
    "-Wclippy::iter_with_drain",
    "-Wclippy::large_stack_frames",
    "-Wclippy::mutex_integer",
    "-Wclippy::needless_collect",
    "-Wclippy::needless_pass_by_ref_mut",
    "-Wclippy::nonstandard_macro_braces",
    "-Wclippy::path_buf_push_overwrite",
    "-Wclippy::redundant_clone",
    "-Wclippy::redundant_pub_crate",
    # "-Wclippy::set_contains_or_insert",
    "-Wclippy::significant_drop_in_scrutinee",
    "-Wclippy::string_lit_as_bytes",
    "-Wclippy::suspicious_operation_groupings",
    "-Wclippy::trailing_empty_array",
    "-Wclippy::trait_duplication_in_bounds",
    "-Wclippy::tuple_array_conversions",
    "-Wclippy::type_repetition_in_bounds",
    "-Wclippy::uninhabited_references",
    "-Wclippy::unnecessary_struct_initialization",
    "-Wclippy::unused_peekable",
    "-Wclippy::unused_rounding",
    # "-Wclippy::while_float",

    # Pedantic Group
    "-Wclippy::bool_to_int_with_if",
    "-Wclippy::checked_conversions",
    "-Wclippy::cloned_instead_of_copied",
    "-Wclippy::copy_iterator",
    "-Wclippy::default_trait_access",
    "-Wclippy::empty_enum",
    "-Wclippy::expl_impl_clone_on_copy",
    "-Wclippy::explicit_into_iter_loop",
    "-Wclippy::filter_map_next",
    "-Wclippy::flat_map_option",
    "-Wclippy::fn_params_excessive_bools",
    "-Wclippy::from_iter_instead_of_collect",
    "-Wclippy::implicit_clone",
    "-Wclippy::index_refutable_slice",
    "-Wclippy::inefficient_to_string",
    "-Wclippy::invalid_upcast_comparisons",
    "-Wclippy::iter_filter_is_ok",
    "-Wclippy::iter_filter_is_some",
    "-Wclippy::iter_not_returning_iterator",
    "-Wclippy::large_digit_groups",
    "-Wclippy::large_futures",
    "-Wclippy::large_stack_arrays",
    "-Wclippy::large_types_passed_by_value",
    "-Wclippy::linkedlist",
    "-Wclippy::macro_use_imports",
    "-Wclippy::manual_assert",
    "-Wclippy::manual_instant_elapsed",
    "-Wclippy::manual_is_variant_and",
    "-Wclippy::manual_ok_or",
    "-Wclippy::manual_string_new",
    "-Wclippy::many_single_char_names",
    "-Wclippy::map_unwrap_or",
    "-Wclippy::match_bool",
    "-Wclippy::match_on_vec_items",
    "-Wclippy::match_same_arms",
    "-Wclippy::match_wildcard_for_single_variants",
    "-Wclippy::maybe_infinite_iter",
    "-Wclippy::mismatching_type_param_order",
    "-Wclippy::missing_fields_in_debug",
    "-Wclippy::mut_mut",
    "-Wclippy::naive_bytecount",
    "-Wclippy::needless_bitwise_bool",
    "-Wclippy::needless_continue",
    "-Wclippy::needless_for_each",
    "-Wclippy::needless_raw_string_hashes",
    "-Wclippy::no_effect_underscore_binding",
    "-Wclippy::no_mangle_with_rust_abi",
    "-Wclippy::ref_option_ref",
    "-Wclippy::option_as_ref_cloned",
    "-Wclippy::pub_underscore_fields",
    "-Wclippy::range_minus_one",
    "-Wclippy::range_plus_one",
    "-Wclippy::redundant_else",
    "-Wclippy::ref_binding_to_reference",
    "-Wclippy::same_functions_in_if_condition",
    "-Wclippy::semicolon_if_nothing_returned",
    "-Wclippy::stable_sort_primitive",
    "-Wclippy::str_split_at_newline",
    "-Wclippy::string_add_assign",
    "-Wclippy::unchecked_duration_subtraction",
    "-Wclippy::unicode_not_nfc",
    "-Wclippy::uninlined_format_args",
    "-Wclippy::unnecessary_box_returns",
    "-Wclippy::unnested_or_patterns",
    "-Wclippy::unsafe_derive_deserialize",
    "-Wclippy::used_underscore_binding",
    "-Wclippy::verbose_bit_mask",
    "-Wclippy::zero_sized_map_values",

    # Restriction Group
    "-Wclippy::alloc_instead_of_core",
    "-Wclippy::big_endian_bytes",
    # "-Wclippy::cfg_not_test",
    "-Wclippy::dbg_macro",
    "-Wclippy::default_union_representation",
    "-Wclippy::empty_drop",
    "-Wclippy::empty_enum_variants_with_brackets",
    "-Wclippy::empty_structs_with_brackets",
    "-Wclippy::exit",
    "-Wclippy::filetype_is_file",
    "-Wclippy::float_cmp_const",
    "-Wclippy::get_unwrap",
    "-Wclippy::host_endian_bytes",
    "-Wclippy::impl_trait_in_params",
    "-Wclippy::infinite_loop",
    "-Wclippy::large_include_file",
    "-Wclippy::lossy_float_literal",
    "-Wclippy::missing_asserts_for_indexing",
    "-Wclippy::mixed_read_write_in_expression",
    "-Wclippy::modulo_arithmetic",
    "-Wclippy::multiple_inherent_impl",
    "-Wclippy::mutex_atomic",
    "-Wclippy::needless_raw_strings",
    # "-Wclippy::pathbuf_init_then_push",
    "-Wclippy::partial_pub_fields",
    "-Wclippy::print_stdout",
    "-Wclippy::pub_without_shorthand",
    "-Wclippy::rc_buffer",
    "-Wclippy::rc_mutex",
    "-Wclippy::redundant_type_annotations",
    "-Wclippy::rest_pat_in_fully_bound_structs",
    "-Wclippy::separated_literal_suffix",
    "-Wclippy::string_lit_chars_any",
    "-Wclippy::string_slice",
    "-Wclippy::string_to_string",
    "-Wclippy::tests_outside_test_module",
    "-Wclippy::unnecessary_self_imports",
    "-Wclippy::unneeded_field_pattern",
    "-Wclippy::use_debug",
    "-Wclippy::verbose_file_reads",
]
