name: Compatibility

on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        # ubuntu-latest, 
        platform: [ubuntu-24.04-arm]
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set timezone
        run: sudo timedatectl set-timezone Asia/Shanghai

      - name: Get TDengine
        run: wget https://github.com/taosdata/TDengine/releases/download/ver-3.3.6.0/TDengine-server-3.3.6.0-Linux-x64.tar.gz

      - name: Install TDengine
        run: |
          tar -zxf TDengine-server-3.3.6.0-Linux-x64.tar.gz
          rm -rf TDengine-server-3.3.6.0-Linux-x64.tar.gz
          cd TDengine-server-3.3.6.0
          sudo ./install.sh -e no

      - name: Copy taos.cfg
        run: |
          sudo mkdir -p /etc/taos
          sudo cp ./.github/workflows/taos.cfg /etc/taos/taos.cfg

      - name: Start TDengine
        run: |
          sudo mkdir -p /mnt/taos/data /mnt/taos/log
          sudo chown -R "$USER":"$(id -gn)" /mnt/taos
          taosd &
          TAOS_ADAPTER_LOG_PATH=/mnt/taos/log taosadapter &

      - name: Start Nginx
        run: |
          sudo nginx -p "$PWD" -c taos-ws/tests/nginx/tls12.conf
          sudo nginx -p "$PWD" -c taos-ws/tests/nginx/tls13.conf
          sudo nginx -p "$PWD" -c taos-ws/tests/nginx/verify_ca.conf
          sudo nginx -p "$PWD" -c taos-ws/tests/nginx/verify_identity.conf

      - name: Set up Rust
        id: setup-rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.90.0
          # targets: aarch64-unknown-linux-gnu

      - name: Install cargo-nextest
        uses: taiki-e/install-action@cargo-nextest

      # - name: Cache .cargo
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       ~/.cargo/bin/
      #       ~/.cargo/registry/index/
      #       ~/.cargo/registry/cache/
      #       ~/.cargo/git/db/
      #     key: ${{ runner.os }}-cargo-${{ steps.setup-rust.outputs.rustc_hash }}

      # - name: Cache target
      #   uses: actions/cache@v4
      #   with:
      #     path: target
      #     key: ${{ runner.os }}-taos-target-${{ steps.setup-rust.outputs.rustc_hash }}

      - name: Test C WebSocket version info
        run: |
          TD_VERSION=3.9.9.9 cargo nextest run -p taos-ws-sys test_taos_get_client_info_injected -- --ignored
          TD_VERSION="$(printf '\xff\xfe')" cargo nextest run -p taos-ws-sys test_taos_get_client_info_default

      - name: Run tests
        env:
          TDENGINE_CLOUD_URL: ${{ secrets.TDENGINE_CLOUD_URL }}
          TDENGINE_CLOUD_TOKEN: ${{ secrets.TDENGINE_CLOUD_TOKEN }}
        run: |
          sed -i 's/crate-type = \["cdylib", "staticlib"\]/crate-type = ["rlib"]/' taos-ws-sys/Cargo.toml
          RUST_BACKTRACE=1 cargo nextest run -j 4 --workspace \
            --features ws-rustls-ring-crypto-provider,test-tls \
            --no-fail-fast
